# Generated by Django 2.1.4 on 2019-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='correct',
        ),
        migrations.AddField(
            model_name='testquestionvariant',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
