# Generated by Django 2.1.4 on 2019-01-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190104_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstest', to='core.Test'),
        ),
    ]
