# Generated by Django 2.1.4 on 2019-01-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190104_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='studenttest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studenttestanswer',
            name='studentTest',
        ),
        migrations.RemoveField(
            model_name='studenttestanswer',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testquestionvariant',
            name='question',
        ),
        migrations.DeleteModel(
            name='StudentTest',
        ),
        migrations.DeleteModel(
            name='StudentTestAnswer',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='TestQuestionVariant',
        ),
    ]
