# Generated by Django 2.1.4 on 2019-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190105_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=244)),
                ('lastName', models.CharField(max_length=244)),
                ('profession', models.CharField(max_length=244)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
