# Generated by Django 2.1.4 on 2019-01-05 11:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('slug', models.CharField(max_length=244)),
                ('date', models.DateTimeField()),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='events')),
            ],
        ),
    ]
