# Generated by Django 2.1.4 on 2019-01-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preText',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
