# Generated by Django 2.1.4 on 2019-01-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=244),
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
