# Generated by Django 2.1.4 on 2019-01-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20190106_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
