# Generated by Django 2.1.4 on 2019-01-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20190106_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentsTests', to='tests.Test'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='totalPoints',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttestanswer',
            name='studentTest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentTestAnswers', to='tests.StudentTest'),
        ),
        migrations.AlterField(
            model_name='studenttestanswer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentVariant', to='tests.TestQuestionVariant'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testQuestions', to='tests.Test'),
        ),
        migrations.AlterField(
            model_name='testquestionvariant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testQuestionVariants', to='tests.TestQuestion'),
        ),
    ]
