# Generated by Django 2.1.4 on 2019-01-08 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0007_auto_20190108_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestanswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userAnswers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
