# Generated by Django 2.1.4 on 2019-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_studenttestanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='inProgress',
            field=models.BooleanField(default=True),
        ),
    ]
